# HTTP
PATCH http://localhost:3000/api/wilders/ HTTP/1.1
content-type: application/json

{
    "identity": {
        "name": "Da Silva",
        "firstName": "Tommy",
        "age": 16
    },
    "skills": [
        {"title": "Rien", "votes": 8}
    ]
}