# HTTP
PATCH http://localhost:3000/api/wilders/5fa27f6d6e36c029382fa0e3 HTTP/1.1
content-type: application/json

{
    "identity": {
        "name": "Testas",
        "firstName": "Lol",
        "age": 19
    },
    "skills": [
        {"title": "NodeJS", "votes": 5}
    ]
}